### ISSUE TITLE
Conflicting peer dependency

### ISSUE THREAD

**Issue by nmerget** [guidepup/guidepup-playwright#21]
# Issue

Setup:

- Node version: v20.16.0
- Guidepup version: 0.24.0
- Guidepup Playwright version: 0.14.1
- OS Platform: windows

## Details
@cmorten 
Somehow we cannot install the Guidepup version `0.24.0` it throws an `Conflicting peer dependency`. It rather works local nor in [Github Actions](https://github.com/db-ui/mono/actions/runs/12021926116/job/33525925532?pr=3510#step:3:63). 
I'm wondering why it isn't working, because you use the caret [here](https://github.com/guidepup/guidepup-playwright/blob/main/package.json#L59) which should work with `0.24.0` as well.

**Comment by jlp-craigmorten** [comment]
Hi @nmerget 👋 

Thanks for raising! Unfortunately I'd missed that `0.x` ranges behave slightly differently with `^` ranges.

Can you try https://github.com/guidepup/guidepup-playwright/releases/tag/0.14.2 and see if it resolves?

**Comment by nmerget** [comment]
[Works](https://github.com/db-ui/mono/pull/3533) thank you @jlp-craigmorten <3
